export const MOCK_AGENCIES = [
  {
    id: '1',
    name: 'Chandler Police Department',
    city: 'Chandler',
    state: 'AZ',
    type: 'Police Department',
    slug: 'chandler-police-department-az',
    overall_grade: 'B',
    review_count: 14,
    command_staff: [
      { id: 'cs1', name: 'Chief Sean Duggan', title: 'Chief of Police' },
      { id: 'cs2', name: 'Deputy Chief Mark Sutton', title: 'Deputy Chief' },
      { id: 'cs3', name: 'Cmdr. Lisa Park', title: 'Commander, Patrol' },
      { id: 'cs4', name: 'Cmdr. Ray Torres', title: 'Commander, Investigations' },
      { id: 'cs5', name: 'Lt. Jennifer Walsh', title: 'Lieutenant, Traffic' },
      { id: 'cs6', name: 'Lt. David Kim', title: 'Lieutenant, Training' },
    ],
  },
  {
    id: '2',
    name: 'Los Angeles Police Department',
    city: 'Los Angeles',
    state: 'CA',
    type: 'Police Department',
    slug: 'los-angeles-police-department-ca',
    overall_grade: 'C',
    review_count: 87,
    command_staff: [
      { id: 'cs7', name: 'Chief Dominic Choi', title: 'Chief of Police' },
      { id: 'cs8', name: 'Dep. Chief Blake Chow', title: 'Deputy Chief, Operations' },
    ],
  },
  {
    id: '3',
    name: 'Phoenix Police Department',
    city: 'Phoenix',
    state: 'AZ',
    type: 'Police Department',
    slug: 'phoenix-police-department-az',
    overall_grade: 'D',
    review_count: 42,
    command_staff: [
      { id: 'cs9', name: 'Chief Michael Sullivan', title: 'Chief of Police' },
    ],
  },
  {
    id: '4',
    name: 'Maricopa County Sheriff\'s Office',
    city: 'Phoenix',
    state: 'AZ',
    type: 'Sheriff\'s Office',
    slug: 'maricopa-county-sheriffs-office-az',
    overall_grade: 'F',
    review_count: 31,
    command_staff: [
      { id: 'cs10', name: 'Sheriff Russ Skinner', title: 'Sheriff' },
    ],
  },
  {
    id: '5',
    name: 'Denver Police Department',
    city: 'Denver',
    state: 'CO',
    type: 'Police Department',
    slug: 'denver-police-department-co',
    overall_grade: 'B',
    review_count: 19,
    command_staff: [],
  },
  {
    id: '6',
    name: 'Seattle Police Department',
    city: 'Seattle',
    state: 'WA',
    type: 'Police Department',
    slug: 'seattle-police-department-wa',
    overall_grade: 'C',
    review_count: 28,
    command_staff: [],
  },
  {
    id: '7',
    name: 'New York Police Department',
    city: 'New York',
    state: 'NY',
    type: 'Police Department',
    slug: 'new-york-police-department-ny',
    overall_grade: 'C',
    review_count: 203,
    command_staff: [],
  },
  {
    id: '8',
    name: 'Chicago Police Department',
    city: 'Chicago',
    state: 'IL',
    type: 'Police Department',
    slug: 'chicago-police-department-il',
    overall_grade: 'D',
    review_count: 156,
    command_staff: [],
  },
  {
    id: '9',
    name: 'Harris County Sheriff\'s Office',
    city: 'Houston',
    state: 'TX',
    type: 'Sheriff\'s Office',
    slug: 'harris-county-sheriffs-office-tx',
    overall_grade: 'B',
    review_count: 11,
    command_staff: [],
  },
  {
    id: '10',
    name: 'Miami-Dade Police Department',
    city: 'Miami',
    state: 'FL',
    type: 'Police Department',
    slug: 'miami-dade-police-department-fl',
    overall_grade: 'A',
    review_count: 7,
    command_staff: [],
  },
];

export const MOCK_AGENCY_REVIEWS = [
  {
    id: 'r1',
    overall_grade: 'A',
    grade_communication: 'A',
    grade_fairness: 'B',
    grade_accountability: 'A',
    grade_backing_officers: 'A',
    grade_toxic_behavior: 'A',
    grade_promotion_fairness: 'B',
    grade_work_life: 'A',
    grade_morale_impact: 'A',
    review_text: 'Command actually listens. Felt supported after a use-of-force review. Promotions are competitive but fair. Work-life has improved significantly under current chief.',
    created_at: '2025-04-10T14:22:00Z',
    users: { username: 'lateral_az_23' },
  },
  {
    id: 'r2',
    overall_grade: 'B',
    grade_communication: 'B',
    grade_fairness: 'B',
    grade_accountability: 'C',
    grade_backing_officers: 'B',
    grade_toxic_behavior: 'B',
    grade_promotion_fairness: 'C',
    grade_work_life: 'A',
    grade_morale_impact: 'B',
    review_text: 'Mid-level management can be inconsistent but upper command is solid. Promotions are where it falls apart — still too much who-you-know.',
    created_at: '2025-03-28T09:15:00Z',
    users: { username: 'ofc_veteran_12' },
  },
  {
    id: 'r3',
    overall_grade: 'B',
    grade_communication: 'A',
    grade_fairness: 'B',
    grade_accountability: 'B',
    grade_backing_officers: 'B',
    grade_toxic_behavior: 'A',
    grade_promotion_fairness: 'B',
    grade_work_life: 'B',
    grade_morale_impact: 'B',
    review_text: null,
    created_at: '2025-02-14T16:40:00Z',
    users: { username: 'recruit_2024' },
  },
];

export const MOCK_SUPERVISOR_REVIEWS = [
  {
    id: 'sr1',
    rank: 'Sergeant',
    overall_grade: 'A',
    grade_communication: 'A',
    grade_fairness: 'A',
    grade_accountability: 'A',
    grade_backing_officers: 'A',
    grade_toxic_behavior: 'A',
    grade_promotion_fairness: 'B',
    grade_work_life: 'A',
    grade_morale_impact: 'A',
    review_text: 'Best supervisors I\'ve worked under. They stand in front of their people, not behind them. Night and day difference from my last agency.',
    created_at: '2025-04-05T11:00:00Z',
    users: { username: 'lateral_az_23' },
  },
  {
    id: 'sr2',
    rank: 'Lieutenant',
    overall_grade: 'C',
    grade_communication: 'C',
    grade_fairness: 'C',
    grade_accountability: 'D',
    grade_backing_officers: 'C',
    grade_toxic_behavior: 'B',
    grade_promotion_fairness: 'C',
    grade_work_life: 'B',
    grade_morale_impact: 'C',
    review_text: 'Lieutenants tend to disappear when things get complicated. Not bad people, just not leaders.',
    created_at: '2025-03-01T08:30:00Z',
    users: { username: 'ofc_veteran_12' },
  },
];

export const MOCK_QUESTIONS = [
  {
    id: 'q1',
    body: 'How does command handle officer-involved shooting reviews? Is it fair or does it feel political?',
    created_at: '2025-04-12T10:00:00Z',
    users: { username: 'prospective_lateral' },
    question_replies: [
      {
        id: 'qr1',
        body: 'In my experience the process is thorough and mostly fair. The chief has been consistent about not throwing officers under the bus for gray-area calls.',
        created_at: '2025-04-12T14:30:00Z',
        users: { username: 'lateral_az_23' },
      },
      {
        id: 'qr2',
        body: 'Agreed. Had one myself and felt like they genuinely reviewed the totality. Union rep said it\'s one of the better departments for that.',
        created_at: '2025-04-13T09:10:00Z',
        users: { username: 'ofc_veteran_12' },
      },
    ],
  },
  {
    id: 'q2',
    body: 'What\'s the lateral hiring process like? Timeline from application to academy start?',
    created_at: '2025-04-01T15:00:00Z',
    users: { username: 'det_applicant' },
    question_replies: [
      {
        id: 'qr3',
        body: 'Took about 4 months for me. Background was thorough. Poly was standard. They moved faster than most agencies I\'ve tested with.',
        created_at: '2025-04-02T08:45:00Z',
        users: { username: 'recruit_2024' },
      },
    ],
  },
  {
    id: 'q3',
    body: 'Is there actually a work-life balance here or is that just recruiting talk?',
    created_at: '2025-03-20T12:00:00Z',
    users: { username: 'tired_of_overtime' },
    question_replies: [],
  },
];
