export const MOCK_AGENCIES = [
  {
    id: 'agency-1',
    name: 'Chandler Police Department',
    city: 'Chandler',
    state: 'AZ',
    type: 'Police Department',
    slug: 'chandler-police-department-az',
    overall_grade: 'B',
    review_count: 14,
    command_staff: [
      { id: 'cs1', name: 'Chief Sean Duggan', title: 'Chief of Police' },
      { id: 'cs2', name: 'Deputy Chief Mark Sutton', title: 'Deputy Chief' },
      { id: 'cs3', name: 'Cmdr. Lisa Park', title: 'Commander, Patrol' },
      { id: 'cs4', name: 'Cmdr. Ray Torres', title: 'Commander, Investigations' },
      { id: 'cs5', name: 'Lt. Jennifer Walsh', title: 'Lieutenant, Traffic' },
      { id: 'cs6', name: 'Lt. David Kim', title: 'Lieutenant, Training' },
    ],
  },
  {
    id: 'agency-2',
    name: 'Los Angeles Police Department',
    city: 'Los Angeles',
    state: 'CA',
    type: 'Police Department',
    slug: 'los-angeles-police-department-ca',
    overall_grade: 'C',
    review_count: 87,
    command_staff: [
      { id: 'cs7', name: 'Chief Dominic Choi', title: 'Chief of Police' },
      { id: 'cs8', name: 'Dep. Chief Blake Chow', title: 'Deputy Chief, Operations' },
    ],
  },
  {
    id: 'agency-3',
    name: 'Phoenix Police Department',
    city: 'Phoenix',
    state: 'AZ',
    type: 'Police Department',
    slug: 'phoenix-police-department-az',
    overall_grade: 'D',
    review_count: 42,
    command_staff: [
      { id: 'cs9', name: 'Chief Michael Sullivan', title: 'Chief of Police' },
    ],
  },
  {
    id: 'agency-4',
    name: "Maricopa County Sheriff's Office",
    city: 'Phoenix',
    state: 'AZ',
    type: "Sheriff's Office",
    slug: 'maricopa-county-sheriffs-office-az',
    overall_grade: 'F',
    review_count: 31,
    command_staff: [
      { id: 'cs10', name: 'Sheriff Russ Skinner', title: 'Sheriff' },
    ],
  },
  {
    id: 'agency-5',
    name: 'Denver Police Department',
    city: 'Denver',
    state: 'CO',
    type: 'Police Department',
    slug: 'denver-police-department-co',
    overall_grade: 'B',
    review_count: 19,
    command_staff: [],
  },
  {
    id: 'agency-6',
    name: 'Seattle Police Department',
    city: 'Seattle',
    state: 'WA',
    type: 'Police Department',
    slug: 'seattle-police-department-wa',
    overall_grade: 'C',
    review_count: 28,
    command_staff: [],
  },
  {
    id: 'agency-7',
    name: 'New York Police Department',
    city: 'New York',
    state: 'NY',
    type: 'Police Department',
    slug: 'new-york-police-department-ny',
    overall_grade: 'C',
    review_count: 203,
    command_staff: [],
  },
  {
    id: 'agency-8',
    name: 'Chicago Police Department',
    city: 'Chicago',
    state: 'IL',
    type: 'Police Department',
    slug: 'chicago-police-department-il',
    overall_grade: 'D',
    review_count: 156,
    command_staff: [],
  },
  {
    id: 'agency-9',
    name: "Harris County Sheriff's Office",
    city: 'Houston',
    state: 'TX',
    type: "Sheriff's Office",
    slug: 'harris-county-sheriffs-office-tx',
    overall_grade: 'B',
    review_count: 11,
    command_staff: [],
  },
  {
    id: 'agency-10',
    name: 'Miami-Dade Police Department',
    city: 'Miami',
    state: 'FL',
    type: 'Police Department',
    slug: 'miami-dade-police-department-fl',
    overall_grade: 'A',
    review_count: 7,
    command_staff: [],
  },
  {
    id: 'agency-11',
    name: 'Houston Police Department',
    city: 'Houston',
    state: 'TX',
    type: 'Police Department',
    slug: 'houston-police-department-tx',
    overall_grade: 'C',
    review_count: 38,
    command_staff: [],
  },
  {
    id: 'agency-12',
    name: 'Las Vegas Metropolitan Police Department',
    city: 'Las Vegas',
    state: 'NV',
    type: 'Police Department',
    slug: 'las-vegas-metro-police-department-nv',
    overall_grade: 'B',
    review_count: 22,
    command_staff: [],
  },
];

export const MOCK_SUPERVISORS = [
  {
    id: 'sup-1',
    agency_id: 'agency-1',
    display_name: 'Sean Duggan',
    rank: 'Chief of Police / Sheriff',
    slug: 'sean-duggan-chandler-pd',
    overall_grade: 'B',
    review_count: 9,
    preview: 'Duggan does a solid job setting the cultural tone. Not perfect, but visible and accountable.',
  },
  {
    id: 'sup-2',
    agency_id: 'agency-1',
    display_name: 'Mark Sutton',
    rank: 'Deputy Chief',
    slug: 'mark-sutton-chandler-pd',
    overall_grade: 'C',
    review_count: 5,
    preview: 'Competent administrator but officers rarely see him outside of critical incidents.',
  },
  {
    id: 'sup-3',
    agency_id: 'agency-1',
    display_name: 'Lisa Park',
    rank: 'Commander',
    slug: 'lisa-park-chandler-pd',
    overall_grade: 'A',
    review_count: 7,
    preview: 'Commander Park is one of the best supervisors I have worked under in 12 years.',
  },
  {
    id: 'sup-4',
    agency_id: 'agency-1',
    display_name: 'Ray Torres',
    rank: 'Commander',
    slug: 'ray-torres-chandler-pd',
    overall_grade: 'B',
    review_count: 4,
    preview: "Investigations commander. Fair, results-focused. Doesn't micromanage.",
  },
  {
    id: 'sup-5',
    agency_id: 'agency-1',
    display_name: 'Jennifer Walsh',
    rank: 'Lieutenant',
    slug: 'jennifer-walsh-chandler-pd',
    overall_grade: 'B',
    review_count: 6,
    preview: 'Lt. Walsh runs a tight unit but treats people like adults.',
  },
  {
    id: 'sup-6',
    agency_id: 'agency-1',
    display_name: 'David Kim',
    rank: 'Lieutenant',
    slug: 'david-kim-chandler-pd',
    overall_grade: 'A',
    review_count: 8,
    preview: 'Training LT. Has genuinely improved the academy culture since taking over.',
  },
  {
    id: 'sup-7',
    agency_id: 'agency-1',
    display_name: 'Tony Reeves',
    rank: 'Sergeant',
    slug: 'tony-reeves-chandler-pd',
    overall_grade: 'D',
    review_count: 11,
    preview: 'Morale killer. Plays favorites hard. Officers transfer off his shift when possible.',
  },
  {
    id: 'sup-8',
    agency_id: 'agency-1',
    display_name: 'Maria Okonkwo',
    rank: 'Sergeant',
    slug: 'maria-okonkwo-chandler-pd',
    overall_grade: 'A',
    review_count: 13,
    preview: 'Sgt. Okonkwo is the reason people stay at Chandler. She will go to bat for you every single time.',
  },
  {
    id: 'sup-9',
    agency_id: 'agency-2',
    display_name: 'Dominic Choi',
    rank: 'Chief of Police / Sheriff',
    slug: 'dominic-choi-lapd',
    overall_grade: 'C',
    review_count: 14,
    preview: 'Better than recent predecessors but still too political when it matters.',
  },
  {
    id: 'sup-10',
    agency_id: 'agency-2',
    display_name: 'Blake Chow',
    rank: 'Deputy Chief',
    slug: 'blake-chow-lapd',
    overall_grade: 'C',
    review_count: 6,
    preview: 'Decent administrator. Does not rock the boat in either direction.',
  },
];

export const MOCK_AGENCY_REVIEWS = [
  {
    id: 'ar-1',
    overall_grade: 'A',
    grade_communication: 'A',
    grade_fairness: 'B',
    grade_accountability: 'A',
    grade_backing_officers: 'A',
    grade_morale: 'A',
    grade_promotion_fairness: 'B',
    grade_work_life: 'A',
    grade_toxic_leadership: 'A',
    review_text: 'Command actually listens. Felt supported after a use-of-force review. Promotions are competitive but fair. Work-life has improved significantly under current chief.',
    created_at: '2025-04-10T14:22:00Z',
    users: { username: 'lateral_az_23' },
  },
  {
    id: 'ar-2',
    overall_grade: 'B',
    grade_communication: 'B',
    grade_fairness: 'B',
    grade_accountability: 'C',
    grade_backing_officers: 'B',
    grade_morale: 'B',
    grade_promotion_fairness: 'C',
    grade_work_life: 'A',
    grade_toxic_leadership: 'B',
    review_text: 'Mid-level management can be inconsistent but upper command is solid. Promotions are where it falls apart — still too much who-you-know.',
    created_at: '2025-03-28T09:15:00Z',
    users: { username: 'ofc_veteran_12' },
  },
  {
    id: 'ar-3',
    overall_grade: 'B',
    grade_communication: 'A',
    grade_fairness: 'B',
    grade_accountability: 'B',
    grade_backing_officers: 'B',
    grade_morale: 'B',
    grade_promotion_fairness: 'B',
    grade_work_life: 'B',
    grade_toxic_leadership: 'A',
    review_text: null,
    created_at: '2025-02-14T16:40:00Z',
    users: { username: 'recruit_2024' },
  },
  {
    id: 'ar-4',
    overall_grade: 'C',
    grade_communication: 'C',
    grade_fairness: 'C',
    grade_accountability: 'B',
    grade_backing_officers: 'C',
    grade_morale: 'C',
    grade_promotion_fairness: 'D',
    grade_work_life: 'C',
    grade_toxic_leadership: 'C',
    review_text: 'Agency is average at best. The culture depends entirely on your sergeant. Leadership above sergeant rank is largely disconnected from what happens on patrol.',
    created_at: '2025-01-22T11:05:00Z',
    users: { username: 'seven_year_patrol' },
  },
];

export const MOCK_SUPERVISOR_REVIEWS_BY_SLUG = {
  'sean-duggan-chandler-pd': [
    {
      id: 'sr-1a',
      overall_grade: 'B',
      grade_communication: 'B',
      grade_fairness: 'A',
      grade_accountability: 'B',
      grade_professionalism: 'A',
      grade_retaliation: 'A',
      grade_morale_impact: 'B',
      grade_backing_officers: 'B',
      grade_promotion_fairness: 'B',
      grade_assignment_fairness: 'B',
      review_text: 'Chief Duggan is accessible and has made genuine improvements to the department culture. Still some favoritism at the commander level but nothing traced directly to him.',
      created_at: '2025-04-18T10:00:00Z',
      users: { username: 'lateral_az_23' },
    },
    {
      id: 'sr-1b',
      overall_grade: 'B',
      grade_communication: 'A',
      grade_fairness: 'B',
      grade_accountability: 'B',
      grade_professionalism: 'A',
      grade_retaliation: 'A',
      grade_morale_impact: 'B',
      grade_backing_officers: 'B',
      grade_promotion_fairness: 'C',
      grade_assignment_fairness: 'B',
      review_text: 'More visible than previous chiefs. Still feels political at times with how he handles media pressure.',
      created_at: '2025-03-10T09:00:00Z',
      users: { username: 'ofc_veteran_12' },
    },
  ],
  'maria-okonkwo-chandler-pd': [
    {
      id: 'sr-8a',
      overall_grade: 'A',
      grade_communication: 'A',
      grade_fairness: 'A',
      grade_accountability: 'A',
      grade_professionalism: 'A',
      grade_retaliation: 'A',
      grade_morale_impact: 'A',
      grade_backing_officers: 'A',
      grade_promotion_fairness: 'A',
      grade_assignment_fairness: 'A',
      review_text: "Sgt. Okonkwo changed how I think about supervision. She gives you the tools, trusts you to do the job, and has your back publicly and privately. Best sergeant I've had.",
      created_at: '2025-04-05T11:00:00Z',
      users: { username: 'ofc_veteran_12' },
    },
    {
      id: 'sr-8b',
      overall_grade: 'A',
      grade_communication: 'A',
      grade_fairness: 'A',
      grade_accountability: 'A',
      grade_professionalism: 'A',
      grade_retaliation: 'A',
      grade_morale_impact: 'A',
      grade_backing_officers: 'A',
      grade_promotion_fairness: 'A',
      grade_assignment_fairness: 'A',
      review_text: 'The best. Transferred to her shift after Reeves and the difference is night and day. She leads from the front.',
      created_at: '2025-03-22T15:30:00Z',
      users: { username: 'seven_year_patrol' },
    },
  ],
  'tony-reeves-chandler-pd': [
    {
      id: 'sr-7a',
      overall_grade: 'D',
      grade_communication: 'D',
      grade_fairness: 'D',
      grade_accountability: 'F',
      grade_professionalism: 'C',
      grade_retaliation: 'D',
      grade_morale_impact: 'F',
      grade_backing_officers: 'D',
      grade_promotion_fairness: 'D',
      grade_assignment_fairness: 'D',
      review_text: 'Sgt. Reeves runs his shift through fear and favoritism. If you are not in his circle you will get the worst assignments. Multiple people have transferred specifically to get off his shift.',
      created_at: '2025-03-12T08:30:00Z',
      users: { username: 'seven_year_patrol' },
    },
    {
      id: 'sr-7b',
      overall_grade: 'F',
      grade_communication: 'F',
      grade_fairness: 'D',
      grade_accountability: 'F',
      grade_professionalism: 'D',
      grade_retaliation: 'F',
      grade_morale_impact: 'F',
      grade_backing_officers: 'F',
      grade_promotion_fairness: 'D',
      grade_assignment_fairness: 'D',
      review_text: 'Worst supervisor in 15 years of law enforcement. Creates a toxic climate and HR has been notified multiple times. Nothing changes.',
      created_at: '2025-02-05T07:00:00Z',
      users: { username: 'recruit_2024' },
    },
  ],
};

export const MOCK_QUESTIONS = [
  {
    id: 'q-1',
    body: 'How does command handle officer-involved shooting reviews? Is it fair or does it feel political?',
    created_at: '2025-04-12T10:00:00Z',
    users: { username: 'prospective_lateral' },
    question_replies: [
      {
        id: 'qr-1',
        body: 'In my experience the process is thorough and mostly fair. The chief has been consistent about not throwing officers under the bus for gray-area calls.',
        created_at: '2025-04-12T14:30:00Z',
        users: { username: 'lateral_az_23' },
      },
      {
        id: 'qr-2',
        body: "Agreed. Had one myself and felt like they genuinely reviewed the totality. Union rep said it's one of the better departments for that.",
        created_at: '2025-04-13T09:10:00Z',
        users: { username: 'ofc_veteran_12' },
      },
    ],
  },
  {
    id: 'q-2',
    body: "What's the lateral hiring process like? Timeline from application to academy start?",
    created_at: '2025-04-01T15:00:00Z',
    users: { username: 'det_applicant' },
    question_replies: [
      {
        id: 'qr-3',
        body: "Took about 4 months for me. Background was thorough. Poly was standard. They moved faster than most agencies I've tested with.",
        created_at: '2025-04-02T08:45:00Z',
        users: { username: 'recruit_2024' },
      },
    ],
  },
  {
    id: 'q-3',
    body: 'Is there actually a work-life balance here or is that just recruiting talk?',
    created_at: '2025-03-20T12:00:00Z',
    users: { username: 'tired_of_overtime' },
    question_replies: [],
  },
  {
    id: 'q-4',
    body: 'Any specialties with open spots right now? Specifically interested in K9 or SWAT pipeline.',
    created_at: '2025-03-05T09:00:00Z',
    users: { username: 'swat_track' },
    question_replies: [
      {
        id: 'qr-4',
        body: 'K9 unit had openings last cycle. SWAT is competitive but they do look at laterals seriously especially if you have prior military or tactical experience.',
        created_at: '2025-03-06T14:20:00Z',
        users: { username: 'lateral_az_23' },
      },
    ],
  },
];
